name: Android build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Materialize google services
        run: .ci/materialize.sh $GOOGLE_SERVICES app/google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Build with Gradle
        run: ./gradlew -Pci assembleDebug
        env:
          BARS_KEY: ${{ secrets.BARS_KEY }}
          BARS_IV: ${{ secrets.BARS_IV }}
          MAP_KEY: ${{ secrets.MAP_KEY }}
